// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var Dummy, config, settings;
    Dummy = require('./model');
    config = require('yaml-config');
    settings = config.readConfig('config/app.yaml');
    return app.get("/dummies/admin", function(req, res, next) {
      if ((req.user != null) && req.user.is_admin === true) {
        return Dummy.find().exec(function(err, dummies) {
          if (err) {
            return next(err);
          }
          return res.render("entity_views/dummies/admin.jade", {
            dummies: dummies
          });
        });
      } else {
        return res.render('login.jade');
      }
    });
  };

}).call(this);
