// Generated by CoffeeScript 1.10.0
(function() {
  var DummiesSchema, Schema, config, db, mongoose, settings;

  mongoose = require('mongoose');

  config = require('yaml-config');

  settings = config.readConfig('config/app.yaml');

  Schema = mongoose.Schema;

  db = mongoose.createConnection(settings.mongodb_uri);

  DummiesSchema = new Schema({
    foo: String,
    bar: String,
    baz: String
  });

  module.exports = db.model('Dummy', DummiesSchema);

}).call(this);
