// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    return app.get("/api/v1/foo", function(req, res) {
      return res.json([
        {
          name: 'larry'
        }, {
          name: 'curly'
        }, {
          name: 'moe'
        }
      ]);
    });
  };

}).call(this);
