// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app, passport) {
    app.get("/", function(req, res) {
      return res.render("home.jade");
    });
    app.get("/login", function(req, res) {
      return res.render("login.jade");
    });
    app.get('/logout', function(req, res) {
      req.logout();
      req.flash('passport-success-logout', 'Logged out successfully!');
      return res.redirect('/');
    });
    app.post('/login', passport.authenticate('local'), function(req, res) {
      var redirection_url;
      redirection_url = req.headers.referer.indexOf('/login') === -1 ? req.headers.referer : '/';
      req.flash('passport-success-login', 'Logged in successfully!');
      return res.redirect(redirection_url);
    });
    return require('../entities/users/controller')(app);
  };

}).call(this);
