// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var User, config, settings;
    User = require('./model');
    config = require('yaml-config');
    settings = config.readConfig('config/app.yaml');
    return app.get("/users/admin", function(req, res, next) {
      if ((req.user != null) && req.user.is_admin === true) {
        return User.find().exec(function(err, users) {
          if (err) {
            return next(err);
          }
          return res.render("entity_views/users/admin.jade", {
            users: users
          });
        });
      } else {
        return res.render('login.jade');
      }
    });
  };

}).call(this);
