// Generated by CoffeeScript 1.10.0
(function() {
  var fs, mvc_dest, mvc_scaffold, name, path, replace, root, routes_file, routes_scaffold, scaffolder, views_dest, views_scaffold;

  fs = require('fs-extra');

  path = require('path');

  replace = require('replace');

  root = path.dirname(__dirname);

  name = "" + (process.env.npm_config_plural.toLowerCase());

  mvc_scaffold = path.join(root, "scaffolds/entities/dummies");

  mvc_dest = path.join(root, "entities/" + name);

  views_scaffold = path.join(root, "scaffolds/views/dummies");

  views_dest = path.join(root, "views/entity_views/" + name);

  routes_file = root + "/routes/index.js";

  routes_scaffold = "  require('../entities/" + name + "/controller')(app);";

  String.prototype.capitalizeFirstLetter = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  scaffolder = function(singular, plural) {
    return fs.copy("" + mvc_scaffold, "" + mvc_dest, function(err) {
      if (err) {
        console.error(err);
        return process.exit();
      } else {
        return fs.copy("" + views_scaffold, "" + views_dest, function(err) {
          if (err) {
            console.error(err);
            return process.exit();
          } else {
            return fs.appendFile("" + routes_file, "" + routes_scaffold, function(err) {
              if (err) {
                console.error(err);
                return process.exit();
              } else {
                replace({
                  regex: 'Dummy',
                  replacement: "" + (singular.capitalizeFirstLetter()),
                  paths: ["" + mvc_dest, "" + views_dest],
                  recursive: true,
                  silent: true
                });
                replace({
                  regex: 'Dummies',
                  replacement: "" + (plural.capitalizeFirstLetter()),
                  paths: ["" + mvc_dest, "" + views_dest],
                  recursive: true,
                  silent: true
                });
                replace({
                  regex: 'dummy',
                  replacement: "" + (singular.toLowerCase()),
                  paths: ["" + mvc_dest, "" + views_dest],
                  recursive: true,
                  silent: true
                });
                replace({
                  regex: 'dummies',
                  replacement: "" + (plural.toLowerCase()),
                  paths: ["" + mvc_dest, "" + views_dest],
                  recursive: true,
                  silent: true
                });
                console.log("Successfully generated scaffold " + name + "!");
                return process.exit();
              }
            });
          }
        });
      }
    });
  };

  scaffolder("" + process.env.npm_config_singular, "" + process.env.npm_config_plural);

}).call(this);
