// Generated by CoffeeScript 1.10.0
(function() {
  var express;

  express = require('express');

  module.exports = function(app) {
    return app.use(function(req, res, next) {
      if (req.user != null) {
        res.locals.current_user = req.user["username"];
      } else {
        res.locals.current_user = 'guest';
      }
      return next();
    });
  };

}).call(this);
