// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(passport, LocalStrategy, User) {
    var bcrypt, salt, validatePassword;
    passport.serializeUser(function(user, done) {
      done(null, user.id);
    });
    passport.deserializeUser(function(id, done) {
      User.findById(id, function(err, user) {
        done(err, user);
      });
    });
    bcrypt = require('bcrypt');
    salt = bcrypt.genSaltSync(10);
    validatePassword = function(password, hash) {
      return bcrypt.compareSync(password, hash);
    };
    return passport.use(new LocalStrategy(function(username, password, done) {
      User.findOne({
        username: username
      }, function(err, user) {
        if (err) {
          return done(err);
        }
        if (!user) {
          return done(null, false, {
            message: 'Incorrect username.'
          });
        }
        if (!validatePassword(password, user.password)) {
          return done(null, false, {
            message: 'Incorrect password.'
          });
        }
        return done(null, user);
      });
    }));
  };

}).call(this);
